version: '3.8'
services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:latest

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web      
      - db
      - redis
    volumes:
      - .:/app
    env_file: .env
    entrypoint: ./sidekiq-entrypoint.sh

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - .:/app

volumes:
  dbdata:
